### ISSUE TITLE
Slow performance of multi_agent_simulation due to high asyncio run calls

### ISSUE THREAD

**Issue by tumayt** [semiotic-ai/autoagora-agents#13]
Setup Python 3.10 (64bit) on windows 11

While running the simulation after 2620 iteration, simulation code is halted. After investigating with a profiler, main issue seems to be multiple usage of asyncio run calls.

![image](https://user-images.githubusercontent.com/109538632/204374318-6eff0de1-f65f-4681-9579-3ac6088e52dd.png)

After wrapping the whole execution with a single asyncio run, issue is resolved.
![image](https://user-images.githubusercontent.com/109538632/204373922-6d04a69a-1a85-4f2f-8c19-c22ab2272eeb.png)

**Comment by aasseman** [comment]
Could you open a PR specific to this issue with your solution?

**Comment by tumayt** [comment]
Some execution times from mac pro m1 before changes 33.1 sec and after changes 22 sec.
